### ISSUE TITLE
seeders

### ISSUE THREAD

**Issue by cognitus** [cable8mm/xeed#61]
Hello,

is posible create a seed from database instead from factory? from laravel I only get the seed generated from the .stub

```php
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        {namespace_class}::factory()->count(10)->create();
    }
```

**Comment by cable8mm** [comment]
I'm having trouble grasping your explanation about that. The Xeed don't generate a seed from factory. Could you please provide further clarification on what you mean?

**Comment by cognitus** [comment]
I read on reddit, is posible generate seeder class like [orangehill/iseed](https://github.com/orangehill/iseed), but to run It I only get a class where the factory is seed

**Comment by cable8mm** [comment]
Develop a new command for generating seeders without utilizing factories.

`bin/console faker-seeders` or `php artisan xeed:faker-seeders`
