### ISSUE TITLE
Can't create relations

### ISSUE THREAD

**Issue by EnMaster** [cable8mm/xeed#72]
|Component|Version|
|---|---|
PHP|8.3.2
Laravel|11.29
SO|MacOS 15.0.1
Platform|M2
xeed|1.5.0

### Issue
When i launch `php artisan xeed:relations` the cli return `TABLE_NAME model doesn't exist. Initially, you create models using 'php artisan xeed:models'.`.
The models were generated correctly, but when the command is run, they are not found.

### Workaround
I have edited the `RelationGenerator` class and rewrite the `__construct()` like this:
```PHP
 private function __construct(
        private Table $table,
        private ?string $namespace = null,
        private ?string $destination = null
    ) {
       // if (is_null($destination)) {
            $this->destination = '/my/real/path/of/the/Models';
     //   }
    }
```

**Comment by cable8mm** [comment]
Thank you for reporting a bug. It has been fixed at that time.
